# Generated by Django 4.0.4 on 2022-06-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
    ]
