# Generated by Django 4.0.4 on 2022-06-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_appointmentcreate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentCreate',
        ),
    ]
