# Generated by Django 4.0.4 on 2022-06-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_appointmentcreate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentCreate',
            new_name='Appointment',
        ),
    ]
