# Generated by Django 4.0.4 on 2022-06-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_appointmentcreate_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
    ]
