# Generated by Django 4.0.4 on 2022-06-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
    ]
