# Generated by Django 4.0.4 on 2022-06-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.CharField(choices=[('MASSAGE', 'massage'), ('FACIAL', 'facial'), ('PACKAGE', 'package')], default='massage', max_length=7),
        ),
    ]
