# Generated by Django 4.0.4 on 2022-06-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_remove_appointment_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
