# Generated by Django 4.0.4 on 2022-06-09 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='packagename1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='packagename2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='packagename3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='packageprice1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='packageprice2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='packageprice3',
        ),
    ]
