# Generated by Django 4.0.4 on 2022-06-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_servicedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceDetails',
        ),
    ]
