# Generated by Django 4.0.4 on 2022-06-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_delete_servicedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('price', models.CharField(max_length=4)),
            ],
        ),
    ]
