# Generated by Django 4.0.4 on 2022-06-09 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_servicedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='main_app.service'),
        ),
    ]
