# Generated by Django 4.0.4 on 2022-06-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_servicedetails_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('MASSAGE', 'massage'), ('FACIAL', 'facial'), ('PACKAGE', 'package')], default='massage', max_length=7),
        ),
    ]
