# Generated by Django 4.0.4 on 2022-06-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_alter_appointment_service_alter_review_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
    ]
