# Generated by Django 4.0.4 on 2022-06-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_alter_appointment_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
