# Generated by Django 4.0.4 on 2022-06-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_alter_appointment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
