# Generated by Django 4.0.4 on 2022-06-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_alter_contact_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
