# Generated by Django 4.0.4 on 2022-06-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pk']},
        ),
    ]
