# Generated by Django 4.0.4 on 2022-06-14 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['pk']},
        ),
    ]
